/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "on-secondary": "#2b313c",
            "surface-container-high": "#282a2d",
            "on-secondary-fixed-variant": "#414753",
            "error": "#ffb4ab",
            "primary-fixed-dim": "#8bceff",
            "on-tertiary-container": "#4a1b0b",
            "surface-dim": "#111317",
            "on-primary-fixed-variant": "#004b6f",
            "inverse-primary": "#006492",
            "on-primary": "#00344e",
            "surface-container": "#1e2023",
            "surface-variant": "#333538",
            "tertiary-fixed": "#ffdbd0",
            "tertiary": "#ffb59e",
            "surface-container-lowest": "#0c0e11",
            "inverse-on-surface": "#2f3034",
            "surface-container-low": "#1a1c1f",
            "on-tertiary-fixed": "#380d02",
            "error-container": "#93000a",
            "tertiary-container": "#c67f68",
            "secondary": "#c1c6d6",
            "background": "#111317",
            "primary": "#8bceff",
            "surface": "#111317",
            "on-secondary-fixed": "#161c27",
            "on-secondary-container": "#b3b8c7",
            "secondary-fixed": "#dde2f2",
            "on-tertiary-fixed-variant": "#6f3725",
            "surface-container-highest": "#333538",
            "on-surface": "#e2e2e6",
            "tertiary-fixed-dim": "#ffb59e",
            "surface-bright": "#37393d",
            "on-primary-fixed": "#001e2f",
            "primary-container": "#2599d7",
            "outline": "#89929b",
            "inverse-surface": "#e2e2e6",
            "on-error-container": "#ffdad6",
            "primary-fixed": "#c9e6ff",
            "on-surface-variant": "#bec8d1",
            "on-primary-container": "#002d44",
            "surface-tint": "#8bceff",
            "secondary-fixed-dim": "#c1c6d6",
            "on-error": "#690005",
            "secondary-container": "#434956",
            "on-tertiary": "#532211",
            "outline-variant": "#3f4850",
            "on-background": "#e2e2e6"
        },
        "fontFamily": {
            "headline": ["Space Grotesk", "sans-serif"],
            "body": ["Inter", "sans-serif"],
            "label": ["Space Grotesk", "sans-serif"]
        }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
}
